# Generated by Django 3.2.9 on 2022-01-17 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shoppingapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='admin',
            new_name='admin2',
        ),
    ]
