# Generated by Django 3.2.9 on 2022-02-02 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoppingapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='add_products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pro_id', models.IntegerField(max_length=10)),
                ('category', models.CharField(max_length=40)),
                ('pro_name', models.CharField(max_length=40)),
                ('qty', models.IntegerField(max_length=40)),
                ('mrp', models.IntegerField(max_length=10)),
                ('unit', models.CharField(max_length=30)),
                ('discount', models.IntegerField(max_length=30)),
                ('amount', models.IntegerField(max_length=10)),
            ],
        ),
    ]
