# Generated by Django 3.2.9 on 2022-02-07 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoppingapp', '0003_customers_sells_invoice_data_sells_items'),
    ]

    operations = [
        migrations.AddField(
            model_name='sells_items',
            name='mod',
            field=models.CharField(default='', max_length=30),
        ),
    ]
