# Generated by Django 3.2.9 on 2022-02-08 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoppingapp', '0004_sells_items_mod'),
    ]

    operations = [
        migrations.AddField(
            model_name='add_products',
            name='emp_id',
            field=models.IntegerField(default=0, max_length=30),
        ),
    ]
