# Generated by Django 3.2.9 on 2022-02-20 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoppingapp', '0005_add_products_emp_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='bank_ac',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_name', models.CharField(max_length=50)),
                ('branch', models.CharField(max_length=50)),
                ('ifc', models.CharField(max_length=50)),
                ('ac_type', models.CharField(max_length=50)),
                ('ac_number', models.IntegerField(max_length=50)),
                ('emp_id', models.IntegerField(max_length=10)),
                ('emp_phone', models.IntegerField(max_length=10)),
            ],
        ),
    ]
