# Generated by Django 3.2.9 on 2022-01-20 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shoppingapp', '0005_remove_employee_basicsal'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='employee',
            new_name='employee2',
        ),
    ]
