# Generated by Django 3.2.9 on 2022-03-06 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoppingapp', '0007_bank_ac_emp_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bank_ac',
            name='emp_phone',
            field=models.IntegerField(max_length=20),
        ),
    ]
